Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2023-12, with the labels that each got.

#61 merge :: (#56) signup
  Projects/Core/Sources/Steps/InfoSettingStep.swift
  Projects/Core/Sources/Steps/PasswordSettingStep.swift
  Projects/Core/Sources/Steps/PrivacyStep.swift
  Projects/Core/Sources/Steps/VerifyEmailStep.swift
  Projects/Data/Sources/DataSource/API/StudentsAPI.swift
  Projects/Data/Sources/DataSource/Remote/RemoteStudentsDataSource.swift
  Projects/Data/Sources/Repositories/StudentsRepositoryImpl.swift
  Projects/Domain/Sources/Repositories/StudentsRepository.swift
  Projects/Domain/Sources/UseCases/Students/StudentExistsUseCase.swift
  Projects/Flow/Sources/AppFlow.swift
  Projects/Flow/Sources/Onboarding/OnboardingFlow.swift
  Projects/Flow/Sources/Signin/SigninFlow.swift
  Projects/Flow/Sources/Signup/InfoSettingFlow.swift
  Projects/Flow/Sources/Signup/PasswordSettingFlow.swift
  Projects/Flow/Sources/Signup/PrivacyFlow.swift
  Projects/Flow/Sources/Signup/VerifyEmailFlow.swift
  Projects/Modules/DesignSystem/Sources/Extensions/Int/Int+extract.swift
  Projects/Modules/DesignSystem/Sources/Extensions/Int/Int+secondsToMinutes.swift
  Projects/Modules/DesignSystem/Sources/Extensions/Rx/RxSwift+limitWithOnlyInt.swift
  Projects/Modules/DesignSystem/Sources/Extensions/String/String+Regex.swift
  Projects/Modules/DesignSystem/Sources/Extensions/String/String+dsmEmail.swift
  Projects/Modules/DesignSystem/Sources/TextField/Component/DescriptionView.swift
  Projects/Modules/DesignSystem/Sources/TextField/Component/TextFieldRightStackView.swift
  Projects/Modules/DesignSystem/Sources/TextField/JobisTextField.swift
  Projects/Modules/DesignSystem/Sources/Toast/JobisToast.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewModel.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
  Projects/Presentation/Sources/Signin/SigninViewModel.swift
  Projects/Presentation/Sources/Signup/InfoSetting/InfoSettingViewController.swift
  Projects/Presentation/Sources/Signup/InfoSetting/InfoSettingViewModel.swift
  Projects/Presentation/Sources/Signup/PasswordSetting/PasswordSettingViewController.swift
  Projects/Presentation/Sources/Signup/PasswordSetting/PasswordSettingViewModel.swift
  Projects/Presentation/Sources/Signup/Privacy/PrivacyViewController.swift
  Projects/Presentation/Sources/Signup/Privacy/PrivacyViewModel.swift
  Projects/Presentation/Sources/Signup/Protocol/SignupViewController.swift
  Projects/Presentation/Sources/Signup/SignupViewController.swift
  Projects/Presentation/Sources/Signup/SignupViewModel.swift
  Projects/Presentation/Sources/Signup/VerifyEmail/VerifyEmailViewController.swift
  Projects/Presentation/Sources/Signup/VerifyEmail/VerifyEmailViewModel.swift
Labels: ✨feat

#58 merge :: (#57) 메모리 leak 해결
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
Labels: 👾bug

#66 merge :: (#65) API path 뒤 슬레쉬('/') 제거
  Projects/Data/Sources/DataSource/API/BookmarksAPI.swift
  Projects/Data/Sources/DataSource/API/BugsAPI.swift
  Projects/Data/Sources/DataSource/API/ReviewsAPI.swift
Labels: ♻️refactor

#81 🔗 :: (#78) 알람 뷰 퍼블리싱
  Projects/Core/Sources/Steps/AlarmStep.swift
  Projects/Core/Sources/Steps/HomeStep.swift
  Projects/Core/Sources/Steps/MainStep.swift
  Projects/Flow/Sources/Tabs/Home/AlarmFlow.swift
  Projects/Flow/Sources/Tabs/Home/HomeFlow.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+setTitle .swift
  Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+tabbar.swift
  Projects/Presentation/Sources/Base/BaseTabBarController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewModel.swift
  Projects/Presentation/Sources/Home/Alarm/Cell/AlarmCell.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
Labels: ✨feat

#69 merge :: (#68) unowned to weak
  .github/CODEOWNERS
  Makefile
  Projects/Modules/DesignSystem/Sources/TextField/JobisTextField.swift
  Projects/Presentation/Sources/Base/BaseNavigationController.swift
  Projects/Presentation/Sources/MyPage/Components/ReviewNavigateStackView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewModel.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
  Projects/Presentation/Sources/Signup/Signup/SignupViewController.swift
Labels: ⚡️performance, ♻️refactor

#76 🔗 :: (#72) 로그인 뷰에서 텍스트필드 엔터 시 로그인 호출
  Projects/Modules/DesignSystem/Sources/Color/JOBISSubColor.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UILabel/UILabe+setColorRange.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
Labels: ✨feat, ♻️refactor

#83 🔗 :: (#70) 모집의뢰서 퍼블리싱
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/bookmarkOff.imageset/Bookmark-1.svg
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/bookmarkOff.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/bookmarkOn.imageset/Bookmark.svg
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/bookmarkOn.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/filterIcon.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/filterIcon.imageset/filter.svg
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/searchIcon.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Icons.xcassets/searchIcon.imageset/search.svg
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
Labels: ✨feat

#89 🔗 :: (#48) XCConfig 설정
  .gitignore
  Plugins/ConfigurationPlugin/Plugin.swift
  Plugins/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
  Plugins/ConfigurationPlugin/ProjectDescriptionHelpers/Path+XCConfig.swift
  Plugins/ConfigurationPlugin/ProjectDescriptionHelpers/ProjectDeployTarget.swift
  Plugins/EnviromentPlugin/Plugin.swift
  Plugins/EnviromentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Plugins/EnvironmentPlugin/Plugin.swift
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/JOBIS-DSM-iOS-v2Debug.entitlements
  Projects/App/Project.swift
  Projects/App/Support/Info.plist
  Projects/App/Support/JOBIS-DSM-iOS-v2.entitlements
  Projects/App/Tests/TargetTest.swift
  Projects/Core/Project.swift
  Projects/Core/Tests/TargetTest.swift
  Projects/Data/Project.swift
  Projects/Data/Sources/DataSource/Remote/RemoteBaseDataSource.swift
  Projects/Data/Tests/TargetTest.swift
  Projects/Domain/Project.swift
  Projects/Domain/Tests/TargetTest.swift
  Projects/Flow/Project.swift
  Projects/Flow/Tests/TargetTest.swift
  Projects/Modules/AppNetwork/Project.swift
  Projects/Modules/AppNetwork/Sources/JobisAPI.swift
  Projects/Modules/AppNetwork/Tests/TargetTest.swift
  Projects/Modules/DesignSystem/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/DesignSystem/Demo/Sources/AppDelegate.swift
  Projects/Modules/DesignSystem/Project.swift
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Jobis logo.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Jobis logo.imageset/Jobis logo.png
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Team return logo.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Team return logo.imageset/Team return logo.png
  Projects/Modules/DesignSystem/Resources/Lotties/OnboardingLottie.json
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Modules/DesignSystem/Sources/Image/OnboardingImage.swift
  Projects/Modules/DesignSystem/Sources/Lottie/JobisLottieView.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Project.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Tests/TargetTest.swift
  Tuist/Config.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/CodeSign.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/ResourceFileElements+Template.swift
  Tuist/ProjectDescriptionHelpers/SourceFiles+Template.swift
  ci_scripts/ci_post_clone.sh
  graph.png
Labels: ✨feat

#94 🔗 :: (#90) Struct 네이밍 리팩토링
  Projects/Data/Sources/DTO/Bugs/BugListResponseDTO.swift
  Projects/Data/Sources/DTO/Companies/CompanyListResponseDTO.swift
  Projects/Data/Sources/DTO/Companies/WritableReviewListResponseDTO.swift
  Projects/Data/Sources/DTO/Recruitments/AreaResponseDTO.swift
  Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift
  Projects/Data/Sources/DataSource/API/CompaniesAPI.swift
  Projects/Data/Sources/DataSource/API/RecruitmentsAPI.swift
  Projects/Data/Sources/DataSource/API/ReviewsAPI.swift
  Projects/Data/Sources/DataSource/Remote/RemoteApplicationsDataSource.swift
  Projects/Data/Sources/DataSource/Remote/RemoteBugsDataSource.swift
  Projects/Data/Sources/DataSource/Remote/RemoteCompaniesDataSource.swift
  Projects/Data/Sources/DataSource/Remote/RemoteRecruitmentsDataSource.swift
  Projects/Data/Sources/DataSource/Remote/RemoteReviewsDataSource.swift
  Projects/Data/Sources/Repositories/ApplicationsRepositoryImpl.swift
  Projects/Data/Sources/Repositories/BugsRepositoryImpl.swift
  Projects/Data/Sources/Repositories/CompaniesRepositoryImpl.swift
  Projects/Data/Sources/Repositories/RecruitmentsRepositoryImpl.swift
  Projects/Data/Sources/Repositories/ReviewsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Bugs/BugReportEntity.swift
  Projects/Domain/Sources/Entities/Companies/CompanyEntity.swift
  Projects/Domain/Sources/Entities/Companies/WritableReviewCompanyEntity.swift
  Projects/Domain/Sources/Entities/Recruitments/AreaEntity.swift
  Projects/Domain/Sources/Repositories/ApplicationsRepository.swift
  Projects/Domain/Sources/Repositories/BugsRepository.swift
  Projects/Domain/Sources/Repositories/CompaniesRepository.swift
  Projects/Domain/Sources/Repositories/RecruitmentsRepository.swift
  Projects/Domain/Sources/Repositories/ReviewsRepository.swift
  Projects/Domain/Sources/UseCases/Applications/ApplyCompanyUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/CancelApplyUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/FetchRejectionReasonUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/ReApplyCompanyUseCase.swift
  Projects/Domain/Sources/UseCases/Bugs/FetchBugListUseCase.swift
  Projects/Domain/Sources/UseCases/Companies/FetchCompanyInfoDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Recruitments/FetchRecruitmentDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Reviews/FetchReviewDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Reviews/FetchReviewListUseCase.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/ReviewNavigateView.swift
  Projects/Presentation/Sources/MyPage/Components/ReviewNavigateStackView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
Labels: ♻️refactor
