Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2023-10, with the labels that each got.

#2 merge :: (#1) Base Domain AppNetwork Setting & Auth Domain Setting
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Core/Sources/Base/BaseViewModel.swift
  Projects/Core/Sources/JwtStore/JwtImpl.swift
  Projects/Core/Sources/JwtStore/JwtStore.swift
  Projects/Core/Sources/JwtStore/KeychainAssembly.swift
  Projects/Core/Sources/Steps/MainStep.swift
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/ReissueTokenResponseDTO.swift
  Projects/Data/Sources/DataSource/API/AuthAPI.swift
  Projects/Data/Sources/DataSource/Remote/AuthRemote.swift
  Projects/Data/Sources/DataSource/Remote/BaseRemote.swift
  Projects/Data/Sources/Repositories/AuthRepositoryImpl.swift
  Projects/Data/Sources/TempFile.swift
  Projects/Data/Sources/Utils/String+toJobisDate.swift
  Projects/Domain/Sources/Entities/ReissueAuthorityEntity.swift
  Projects/Domain/Sources/Enums/AuthCodeType.swift
  Projects/Domain/Sources/Enums/AuthorityType.swift
  Projects/Domain/Sources/Error/JobisError.swift
  Projects/Domain/Sources/Error/TokenError.swift
  Projects/Domain/Sources/Parameters/SendAuthCodeRequestQuery.swift
  Projects/Domain/Sources/Repositories/AuthRepository.swift
  Projects/Domain/Sources/TempFile.swift
  Projects/Domain/Sources/UseCases/Auth/ReissueTokenUaseCase.swift
  Projects/Domain/Sources/UseCases/Auth/SendAuthCodeUseCase.swift
  Projects/Domain/Sources/UseCases/Auth/VerifyAuthCodeUseCase.swift
  Projects/Flow/Sources/AppFlow.swift
  Projects/Flow/Sources/AppStepper.swift
  Projects/Flow/Sources/Main/MainFlow.swift
  Projects/Modules/AppNetwork/Sources/JobisAPI.swift
  Projects/Modules/AppNetwork/Sources/Jwt/JwtAuthorizable.swift
  Projects/Modules/AppNetwork/Sources/Jwt/JwtPlugin.swift
  Projects/Modules/AppNetwork/Sources/Jwt/Logging/MoyaLoggingPlugin.swift
  Projects/Modules/AppNetwork/Sources/Jwt/TokenDTO.swift
  Projects/Modules/AppNetwork/Sources/TempFile.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Main/MainViewController.swift
  Projects/Presentation/Sources/Main/MainViewModel.swift
  Scripts/SwiftLintRunScript.sh
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Action+Template.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  graph.png
Labels: ✨feat

#4 merge :: (#3) Users API
  Projects/App/JOBIS-DSM-iOS-v2.entitlements
  Projects/App/Support/Info.plist
  Projects/Core/Sources/JwtStore/JwtImpl.swift
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/AuthTokenResponseDTO.swift
  Projects/Data/Sources/DTO/ReissueTokenResponseDTO.swift
  Projects/Data/Sources/DataSource/API/UsersAPI.swift
  Projects/Data/Sources/DataSource/Remote/AuthRemote.swift
  Projects/Data/Sources/DataSource/Remote/UsersRemote.swift
  Projects/Data/Sources/Repositories/AuthRepositoryImpl.swift
  Projects/Data/Sources/Repositories/UsersRepositoryImpl.swift
  Projects/Domain/Sources/Entities/ReissueAuthorityEntity.swift
  Projects/Domain/Sources/Parameters/SigninRequestQuery.swift
  Projects/Domain/Sources/Repositories/AuthRepository.swift
  Projects/Domain/Sources/Repositories/UsersRepository.swift
  Projects/Domain/Sources/UseCases/Auth/ReissueTokenUaseCase.swift
  Projects/Domain/Sources/UseCases/Users/SigninUseCase.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Main/MainViewController.swift
  Projects/Presentation/Sources/Main/MainViewModel.swift
Labels: ✨feat

#9 merge :: (#7) Companies API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/CompanyInfoDetailResponseDTO.swift
  Projects/Data/Sources/DTO/CompanyListResponseDTO.swift
  Projects/Data/Sources/DTO/WritableReviewListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/CompaniesAPI.swift
  Projects/Data/Sources/DataSource/Remote/CompaniesRemote.swift
  Projects/Data/Sources/Repositories/CompaniesRepositoryImpl.swift
  Projects/Domain/Sources/Entities/CompanyEntity.swift
  Projects/Domain/Sources/Entities/CompanyInfoDetailEntity.swift
  Projects/Domain/Sources/Entities/WritableReviewCompanyEntity.swift
  Projects/Domain/Sources/Repositories/CompaniesRepository.swift
  Projects/Domain/Sources/UseCases/Companies/FetchCompanyInfoDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Companies/FetchCompanyListUseCase.swift
  Projects/Domain/Sources/UseCases/Companies/FetchWritableReviewListUseCase.swift
Labels: ✨feat

#11 merge :: (#6) Students API
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/StudentInfoResponseDTO.swift
  Projects/Data/Sources/DataSource/API/StudentsAPI.swift
  Projects/Data/Sources/DataSource/Remote/StudentsRemote.swift
  Projects/Data/Sources/Repositories/StudentsRepositoryImpl.swift
  Projects/Domain/Sources/Entites/StudentInfoEntity.swift
  Projects/Domain/Sources/Enums/DepartmentType.swift
  Projects/Domain/Sources/Enums/GenderType.swift
  Projects/Domain/Sources/Parameters/ChangePasswordRequestQuery.swift
  Projects/Domain/Sources/Parameters/RenewalPasswordRequestQuery.swift
  Projects/Domain/Sources/Parameters/SignupRequestQuery.swift
  Projects/Domain/Sources/Repositories/StudentsRepository.swift
  Projects/Domain/Sources/UseCases/Students/ChangePasswordUseCase.swift
  Projects/Domain/Sources/UseCases/Students/ChangeProfileImageUseCase.swift
  Projects/Domain/Sources/UseCases/Students/CompareCurrentPassswordUseCase.swift
  Projects/Domain/Sources/UseCases/Students/FetchStudentInfoUseCase.swift
  Projects/Domain/Sources/UseCases/Students/RenewalPasswordUseCase.swift
  Projects/Domain/Sources/UseCases/Students/SignupUseCase.swift
  Projects/Domain/Sources/UseCases/Students/StudentExistsUseCase.swift
Labels: ✨feat

#12 merge :: (#8) DTO public -> internal
  Projects/Data/Sources/DTO/AuthTokenResponseDTO.swift
  Projects/Data/Sources/DTO/CompanyInfoDetailResponseDTO.swift
  Projects/Data/Sources/DTO/CompanyListResponseDTO.swift
  Projects/Data/Sources/DTO/StudentInfoResponseDTO.swift
  Projects/Data/Sources/DTO/WritableReviewListResponseDTO.swift
Labels: ♻️refactor

#13 merge :: (#10) File Segmentation
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Auth/AuthTokenResponseDTO.swift
  Projects/Data/Sources/DTO/Companies/CompanyInfoDetailResponseDTO.swift
  Projects/Data/Sources/DTO/Companies/CompanyListResponseDTO.swift
  Projects/Data/Sources/DTO/Companies/WritableReviewListResponseDTO.swift
  Projects/Data/Sources/DTO/Students/StudentInfoResponseDTO.swift
  Projects/Domain/Sources/Entities/Companies/CompanyEntity.swift
  Projects/Domain/Sources/Entities/Companies/CompanyInfoDetailEntity.swift
  Projects/Domain/Sources/Entities/Companies/WritableReviewCompanyEntity.swift
  Projects/Domain/Sources/Entities/Studetns/StudentInfoEntity.swift
  Projects/Domain/Sources/Parameters/Auth/SendAuthCodeRequestQuery.swift
  Projects/Domain/Sources/Parameters/Students/ChangePasswordRequestQuery.swift
  Projects/Domain/Sources/Parameters/Students/RenewalPasswordRequestQuery.swift
  Projects/Domain/Sources/Parameters/Students/SignupRequestQuery.swift
  Projects/Domain/Sources/Parameters/Users/SigninRequestQuery.swift
Labels: ♻️refactor

#17 merge :: (#16) bugs api
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Bugs/BugDetailResponseDTO.swift
  Projects/Data/Sources/DTO/Bugs/BugListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/BugsAPI.swift
  Projects/Data/Sources/DataSource/Remote/AuthRemote.swift
  Projects/Data/Sources/DataSource/Remote/BugsRemote.swift
  Projects/Data/Sources/DataSource/Remote/CompaniesRemote.swift
  Projects/Data/Sources/DataSource/Remote/ReviewsRemote.swift
  Projects/Data/Sources/DataSource/Remote/StudentsRemote.swift
  Projects/Data/Sources/DataSource/Remote/UsersRemote.swift
  Projects/Data/Sources/Repositories/BugsRepositoryImpl.swift
  Projects/Data/Sources/Repositories/ReviewsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Entity/BugDetailEntity.swift
  Projects/Domain/Sources/Entities/Entity/BugEntity.swift
  Projects/Domain/Sources/Enums/DevelopmentType.swift
  Projects/Domain/Sources/Parameters/Bugs/ReportBugRequestQuery.swift
  Projects/Domain/Sources/Repositories/BugsRepository.swift
  Projects/Domain/Sources/UseCases/Bugs/FetchBugDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Bugs/FetchBugListUseCase.swift
  Projects/Domain/Sources/UseCases/Bugs/ReportBugUseCase.swift
Labels: ✨feat

#21 merge :: (#20) Files API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Files/UploadFilesResponseDTO.swift
  Projects/Data/Sources/DataSource/API/FilesAPI.swift
  Projects/Data/Sources/DataSource/Remote/FilesRemote.swift
  Projects/Data/Sources/Repositories/FilesRepositoryImpl.swift
  Projects/Domain/Sources/Repositories/FilesRepository.swift
  Projects/Domain/Sources/UseCases/Files/UploadFilesUseCase.swift
Labels: ✨feat

#19 merge :: (#18) Codes API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Codes/CodeListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/AuthAPI.swift
  Projects/Data/Sources/DataSource/API/CodesAPI.swift
  Projects/Data/Sources/DataSource/API/CompaniesAPI.swift
  Projects/Data/Sources/DataSource/API/ReviewsAPI.swift
  Projects/Data/Sources/DataSource/API/StudentsAPI.swift
  Projects/Data/Sources/DataSource/API/UsersAPI.swift
  Projects/Data/Sources/DataSource/Remote/CodesRemote.swift
  Projects/Data/Sources/Repositories/CodesRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Bugs/BugDetailEntity.swift
  Projects/Domain/Sources/Entities/Bugs/BugEntity.swift
  Projects/Domain/Sources/Entities/Codes/CodeEntity.swift
  Projects/Domain/Sources/Enums/CodeType.swift
  Projects/Domain/Sources/Repositories/CodesRepository.swift
  Projects/Domain/Sources/UseCases/Codes/FetchCodeListUseCase.swift
Labels: ✨feat

#23 marge :: (#5) Applications API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Applications/ApplicationListResponseDTO.swift
  Projects/Data/Sources/DTO/Applications/AttachmentsResponseDTO.swift
  Projects/Data/Sources/DTO/Applications/TotalPassStudentResponseDTO.swift
  Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift
  Projects/Data/Sources/DataSource/Remote/ApplicationsRemote.swift
  Projects/Data/Sources/Repositories/ApplicationsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Applications/ApplicationEntity.swift
  Projects/Domain/Sources/Entities/Applications/AttachmentsEntity.swift
  Projects/Domain/Sources/Entities/Applications/TotalPassStudentEntity.swift
  Projects/Domain/Sources/Enums/ApplicationStatusType.swift
  Projects/Domain/Sources/Enums/AttachmentType.swift
  Projects/Domain/Sources/Parameters/Applications/ApplyCompanyRequestQuery.swift
  Projects/Domain/Sources/Repositories/ApplicationsRepository.swift
  Projects/Domain/Sources/UseCases/Applications/ApplyCompanyUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/CancelApplyUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/FetchApplicationUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/FetchTotalPassStudentUseCase.swift
Labels: ✨feat

#25 merge :: (#22) Recruitments API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Recruitments/AreaResponseDTO.swift
  Projects/Data/Sources/DTO/Recruitments/RecruitmentDetailResponseDTO.swift
  Projects/Data/Sources/DTO/Recruitments/RecruitmentListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/RecruitmentsAPI.swift
  Projects/Data/Sources/DataSource/Remote/RecruitmentsRemote.swift
  Projects/Data/Sources/Repositories/RecruitmentsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Recruitments/AreaEntity.swift
  Projects/Domain/Sources/Entities/Recruitments/RecruitmentDetailEntity.swift
  Projects/Domain/Sources/Entities/Recruitments/RecruitmentEntity.swift
  Projects/Domain/Sources/Enums/InterviewType.swift
  Projects/Domain/Sources/Repositories/RecruitmentsRepository.swift
  Projects/Domain/Sources/UseCases/Recruitments/FetchRecruitmentDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Recruitments/FetchRecruitmentListUseCase.swift
Labels: ✨feat

#26 merge :: (#24) Bookmarks API
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Bookmarks/BookmarkResponseDTO.swift
  Projects/Data/Sources/DataSource/API/BookmarksAPI.swift
  Projects/Data/Sources/DataSource/Remote/BookmarksRemote.swift
  Projects/Data/Sources/Repositories/BookmarksRepositoryImpl.swift
  Projects/Data/Sources/Utils/Date+toString.swift
  Projects/Domain/Sources/Entities/Bookmarks/BookmarkEntity.swift
  Projects/Domain/Sources/Repositories/BookmarksRepository.swift
  Projects/Domain/Sources/UseCases/Bookmarks/BookmarkUseCase.swift
  Projects/Domain/Sources/UseCases/Bookmarks/FetchBookmarkListUseCase.swift
Labels: ✨feat

#27 merge :: Update README.md
  README.md
Labels: 📝docs
