Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2024-03, with the labels that each got.

#143 🔗 :: (#141) 모집 의뢰서 상세보기, 회사 상세보기 퍼블리싱
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Arrow Down.imageset/Arrow_down.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Arrow Down.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Arrow Up.imageset/Arrow_down.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Arrow Up.imageset/Contents.json
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Presentation/Sources/Recruitment/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/Recruitment/Components/Cell/EmptyInterviewReviewView.swift
  Projects/Presentation/Sources/Recruitment/Components/Cell/FieldTypeDetailViewCell.swift
  Projects/Presentation/Sources/Recruitment/Components/Cell/InterviewReviewTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/Components/Cell/RecruitmentTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/Components/CompanyDetailLabel.swift
  Projects/Presentation/Sources/Recruitment/Components/RecruitmentDetailLabel.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentList/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentList/RecruitmentViewModel.swift
Labels: ✨feat

#147 🔗 :: (#88) Onboarding 로티
  Makefile
  Projects/Modules/DesignSystem/Project.swift
  Projects/Modules/DesignSystem/Resources/Lotties/Dark Onboarding.json
  Projects/Modules/DesignSystem/Resources/Lotties/Light Onboarding.json
  Projects/Modules/DesignSystem/Resources/Lotties/OnboardingLottie.json
  Projects/Modules/DesignSystem/Sources/Button/JobisButton.swift
  Projects/Modules/DesignSystem/Sources/Lottie/JobisLottieView.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewModel.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ResourceSynthesizers/Lottie.stencil
  ci_scripts/ci_install_tuist.sh
  ci_scripts/ci_post_clone.sh
Labels: ✨feat, ♻️refactor

#148 🔗 :: (#146) Notice, Recruitment RxFlow 적용
  Projects/Core/Sources/Steps/CompanyDetailStep.swift
  Projects/Core/Sources/Steps/MyPageStep.swift
  Projects/Core/Sources/Steps/NoticeStep.swift
  Projects/Core/Sources/Steps/RecruitmentDetailStep.swift
  Projects/Core/Sources/Steps/RecruitmentStep.swift
  Projects/Flow/Sources/BookmarkFlow.swift
  Projects/Flow/Sources/CompanyDetailFlow.swift
  Projects/Flow/Sources/Home/AlarmFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Flow/Sources/MyPage/MyPageFlow.swift
  Projects/Flow/Sources/MyPage/Notice/NoticeFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentDetailFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentFlow.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+tabbar.swift
  Projects/Presentation/Sources/Company/CompanyDetailViewController.swift
  Projects/Presentation/Sources/Company/CompanyDetailViewModel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
  Projects/Presentation/Sources/Notice/Cell/AttachedFileTableViewCell.swift
  Projects/Presentation/Sources/Notice/Cell/NoticeTableViewCell.swift
  Projects/Presentation/Sources/Notice/NoticeDetailViewController.swift
  Projects/Presentation/Sources/Notice/NoticeDetailViewModel.swift
  Projects/Presentation/Sources/Notice/NoticeViewController.swift
  Projects/Presentation/Sources/Notice/NoticeViewModel.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewModel.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentList/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentList/RecruitmentViewModel.swift
  graph.png
Labels: ✨feat, ♻️refactor

#157 🔗 :: (#145) 모집의뢰서 상세보기 refactoring
  Projects/Presentation/Sources/Base/BaseTableViewCell.swift
  Projects/Presentation/Sources/CompanyDetail/Cell/InterviewReviewTableViewCell.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewModel.swift
  Projects/Presentation/Sources/CompanyDetail/Components/CompanyDetailLabel.swift
  Projects/Presentation/Sources/CompanyDetail/Components/EmptyInterviewReviewView.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Recruitment/Cell/RecruitmentTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/Components/RecruitmentDetailLabel.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/Cell/FieldTypeDetailViewCell.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/RecruitmentDetailLabel.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: ♻️refactor

#159 🔗 :: (#158) 모집의뢰서 상세보기 api연동
  Projects/Core/Sources/Steps/RecruitmentStep.swift
  Projects/Flow/Sources/Recruitment/RecruitmentFlow.swift
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/List Empty.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/List Empty.imageset/Expressionless face.svg
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Presentation/Sources/Bookmark/BookmarkViewController.swift
  Projects/Presentation/Sources/Bookmark/Component/ListEmptyView.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/Cell/FieldTypeDetailViewCell.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/RecruitmentDetailLabel.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: ✨feat

#176 🔗 :: (#175) 다음에 하기 버튼 추가
  Projects/Presentation/Sources/Signup/ProfileSetting/Components/LaterButton.swift
  Projects/Presentation/Sources/Signup/ProfileSetting/ProfileSettingViewController.swift
  Projects/Presentation/Sources/Signup/ProfileSetting/ProfileSettingViewModel.swift
Labels: ✨feat

#172 🔗 :: (#155) CompanyDetail API 연동
  Projects/Core/Sources/Steps/RecruitmentDetailStep.swift
  Projects/Data/Sources/DTO/Companies/CompanyInfoDetailResponseDTO.swift
  Projects/Data/Sources/DTO/Revies/ReviewListResponseDTO.swift
  Projects/Domain/Sources/Entities/Companies/CompanyInfoDetailEntity.swift
  Projects/Domain/Sources/Entities/Reviews/ReviewEntity.swift
  Projects/Flow/Sources/Company/CompanyDetailFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentDetailFlow.swift
  Projects/Presentation/Sources/CompanyDetail/Cell/InterviewReviewTableViewCell.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewModel.swift
  Projects/Presentation/Sources/CompanyDetail/Components/CompanyDetailLabel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: ✨feat

#180 🔗 :: (#179) NoticeAPI 연동
  Projects/Core/Sources/Steps/NoticeDetailStep.swift
  Projects/Core/Sources/Steps/NoticeStep.swift
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Notice/NoticeDetailResponseDTO.swift
  Projects/Data/Sources/DTO/Notice/NoticeListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/NoticeAPI.swift
  Projects/Data/Sources/DataSource/Remote/RemoteNoticesDataSource.swift
  Projects/Data/Sources/Repositories/NoticesRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Applications/AttachmentsEntity.swift
  Projects/Domain/Sources/Entities/Notice/NoticeDetailEntity.swift
  Projects/Domain/Sources/Entities/Notice/NoticeEntity.swift
  Projects/Domain/Sources/Repositories/NoticesRepository.swift
  Projects/Domain/Sources/UseCases/Notice/FetchNoticeDetailUseCase.swift
  Projects/Domain/Sources/UseCases/Notice/FetchNoticeListUseCase.swift
  Projects/Flow/Sources/MyPage/Notice/NoticeDetailFlow.swift
  Projects/Flow/Sources/MyPage/Notice/NoticeFlow.swift
  Projects/Modules/AppNetwork/Sources/JobisAPI.swift
  Projects/Modules/DesignSystem/Sources/Extensions/DateUtility/Date+Format.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Notice/Cell/AttachedFileTableViewCell.swift
  Projects/Presentation/Sources/Notice/Cell/NoticeTableViewCell.swift
  Projects/Presentation/Sources/Notice/NoticeDetailViewController.swift
  Projects/Presentation/Sources/Notice/NoticeDetailViewModel.swift
  Projects/Presentation/Sources/Notice/NoticeViewController.swift
  Projects/Presentation/Sources/Notice/NoticeViewModel.swift
Labels: ✨feat

#185 🔗 :: (#184) 모집의뢰서 상세보기 response 수정
  Projects/Data/Sources/DTO/Recruitments/AreaResponseDTO.swift
  Projects/Data/Sources/DTO/Recruitments/JobResponseDTO.swift
  Projects/Data/Sources/DTO/Recruitments/TechReponseDTO.swift
Labels: 👾bug

#186 🔗 :: (#181) CompanySearch 퍼블리싱 API
  Projects/Core/Sources/Steps/CompanySearchStep.swift
  Projects/Core/Sources/Steps/HomeStep.swift
  Projects/Domain/Sources/UseCases/Companies/FetchCompanyListUseCase.swift
  Projects/Flow/Sources/Company/CompanySearchFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Presentation/Sources/CompanySearch/CompanySearchViewController.swift
  Projects/Presentation/Sources/CompanySearch/CompanySearchViewModel.swift
  Projects/Presentation/Sources/CompanySearch/Components/Cell/CompanySearchTableViewCell.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Components/CareerNavigationView.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
  Projects/Presentation/Sources/Notice/Cell/NoticeTableViewCell.swift
  Projects/Presentation/Sources/Notice/NoticeViewController.swift
Labels: ✨feat

#188 🔗 :: (#187) Recruitment Design Edit
  Projects/Presentation/Sources/Notice/NoticeViewController.swift
  Projects/Presentation/Sources/Recruitment/Cell/RecruitmentTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
Labels: ✨feat

#189 🔗 :: (#177) 지원하기 구현
  Projects/Core/Sources/Steps/ApplyStep.swift
  Projects/Core/Sources/Steps/RecruitmentDetailStep.swift
  Projects/Data/Sources/DTO/Recruitments/RecruitmentDetailResponseDTO.swift
  Projects/Data/Sources/DataSource/API/RecruitmentsAPI.swift
  Projects/Domain/Sources/Entities/Recruitments/RecruitmentDetailEntity.swift
  Projects/Domain/Sources/UseCases/Applications/ApplyCompanyUseCase.swift
  Projects/Flow/Sources/Apply/ApplyFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentDetailFlow.swift
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Plus.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Plus.imageset/plus.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/close.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/close.imageset/close.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/link.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/link.imageset/link.svg
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Presentation/Sources/Apply/ApplyViewController.swift
  Projects/Presentation/Sources/Apply/ApplyViewModel.swift
  Projects/Presentation/Sources/Apply/Components/AddAttachmentButton.swift
  Projects/Presentation/Sources/Apply/Components/AttachmentStackView.swift
  Projects/Presentation/Sources/Apply/Components/AttachmentView.swift
  Projects/Presentation/Sources/Confirm/ConfirmPassword/ConfirmPasswordViewModel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: ✨feat

#193 🔗 :: (#190) 반려 사유 및 재지원 구현
  Projects/Core/Sources/Steps/ApplyStep.swift
  Projects/Core/Sources/Steps/HomeStep.swift
  Projects/Core/Sources/Steps/RejectReasonStep.swift
  Projects/Data/Sources/DTO/Applications/ApplicationListResponseDTO.swift
  Projects/Data/Sources/DTO/Reviews/QnaResponseDTO.swift
  Projects/Data/Sources/DTO/Reviews/ReviewListResponseDTO.swift
  Projects/Domain/Sources/Entities/Applications/ApplicationEntity.swift
  Projects/Domain/Sources/Enums/ApplicationStatusType.swift
  Projects/Domain/Sources/UseCases/Applications/FetchRejectionReasonUseCase.swift
  Projects/Domain/Sources/UseCases/Applications/ReApplyCompanyUseCase.swift
  Projects/Flow/Sources/Apply/ApplyFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentDetailFlow.swift
  Projects/Flow/Sources/RejectReason/RejectReasonFlow.swift
  Projects/Presentation/Sources/Apply/ApplyViewController.swift
  Projects/Presentation/Sources/Apply/ApplyViewModel.swift
  Projects/Presentation/Sources/Base/BaseBottomSheetViewController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusTableViewCell.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
  Projects/Presentation/Sources/Reject/RejectReasonViewController.swift
  Projects/Presentation/Sources/Reject/RejectReasonViewModel.swift
Labels: ✨feat

#194 🔗 :: (#191) 모집의뢰서 검색 구현
  Projects/Core/Sources/Steps/RecruitmentSearchStep.swift
  Projects/Core/Sources/Steps/RecruitmentStep.swift
  Projects/Flow/Sources/Recruitment/RecruitmentFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentSearchFlow.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentSearch/RecruitmentSearchViewController.swift
  Projects/Presentation/Sources/RecruitmentSearch/RecruitmentSearchViewModel.swift
Labels: ✨feat

#198 🔗 :: (#196) 첫빌드 크러시(충돌) 버그 수정
  .gitignore
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/App/Resources/GoogleService-Info.plist
  Projects/App/Sources/AppDelegate.swift
  Projects/Flow/Sources/RejectReason/RejectReasonFlow.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Modules/ThirdPartyLib/Sources/Void.swift
  Projects/Presentation/Project.swift
  graph.png
Labels: 👾bug

#197 🔗 :: (#195) 지원하기 error 처리 및 자잘한 수정
  Projects/Core/Sources/Steps/ApplyStep.swift
  Projects/Core/Sources/Steps/CompanyDetailStep.swift
  Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift
  Projects/Domain/Sources/Error/ApplicationsError.swift
  Projects/Flow/Sources/Apply/ApplyFlow.swift
  Projects/Flow/Sources/BookmarkFlow.swift
  Projects/Flow/Sources/Company/CompanyDetailFlow.swift
  Projects/Flow/Sources/Company/CompanySearchFlow.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+showJobisToast.swift
  Projects/Modules/DesignSystem/Sources/Toast/JobisToast.swift
  Projects/Presentation/Sources/Apply/ApplyViewModel.swift
  Projects/Presentation/Sources/Base/BaseTabBarController.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewModel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/Cell/FieldTypeDetailViewCell.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/CompanyProfileView.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/RecruitmentDetailLabel.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: 👾bug, ✨feat

#200 🔗 :: (#199) 알림 api 연동
  Projects/Data/Sources/DI/DataSourceAssembly.swift
  Projects/Data/Sources/DI/RepositoryAssembly.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Notifications/NotificationListDTO.swift
  Projects/Data/Sources/DataSource/API/NotificationsAPI.swift
  Projects/Data/Sources/DataSource/Remote/RemoteNotificationsDataSource.swift
  Projects/Data/Sources/Repositories/NotificationsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Notifications/NotificationEntity.swift
  Projects/Domain/Sources/Repositories/NotificationsRepository.swift
  Projects/Domain/Sources/UseCases/Notifications/FetchNotificationListUseCase.swift
  Projects/Domain/Sources/UseCases/Notifications/ReadNotificationUseCase.swift
  Projects/Modules/AppNetwork/Sources/JobisAPI.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewModel.swift
  Projects/Presentation/Sources/Home/Alarm/Cell/AlarmTableViewCell.swift
Labels: ✨feat

#211 🔗 :: (#210) 배포 전 리펙토링
  Projects/Flow/Sources/Recruitment/RecruitmentFlow.swift
  Projects/Presentation/Sources/Recruitment/Cell/RecruitmentTableViewCell.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/FieldTypeDetailStackView.swift
  Projects/Presentation/Sources/RecruitmentDetail/Components/FieldTypeDetailView.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentSearch/RecruitmentSearchViewController.swift
Labels: ♻️refactor
