Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2024-01, with the labels that each got.

#101 🔗 :: (#100) 로그인, 토큰재발급, 회원가입에 platformType 추가
  Projects/Data/Sources/DataSource/API/AuthAPI.swift
  Projects/Domain/Sources/Parameters/Students/SignupRequestQuery.swift
  Projects/Domain/Sources/Parameters/Users/SigninRequestQuery.swift
Labels: ✨feat

#99 🔗 :: (#98) BaseRemoteDataSource 파일 명 수정
  Projects/Data/Sources/DataSource/Remote/Base/BaseRemoteDataSource.swift
  Projects/Modules/AppNetwork/Sources/Plugins/Jwt/JwtAuthorizable.swift
  Projects/Modules/AppNetwork/Sources/Plugins/Jwt/JwtPlugin.swift
  Projects/Modules/AppNetwork/Sources/Plugins/Jwt/TokenDTO.swift
  Projects/Modules/AppNetwork/Sources/Plugins/Logging/MoyaLoggingPlugin.swift
Labels: ♻️refactor

#107 🔗 :: (#106) totalStudentCount가 0일 때 1로 처리
  Projects/Domain/Sources/Entities/Applications/TotalPassStudentEntity.swift
Labels: ♻️refactor

#104 🔗 :: (#102) 로그아웃, 회원탈퇴 구현
  Projects/Core/Sources/Steps/MyPageStep.swift
  Projects/Core/Sources/Steps/TabsStep.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Flow/Sources/Tabs/MyPageFlow.swift
  Projects/Flow/Sources/Tabs/TabsFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/SectionCollectionViewCell.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
Labels: ✨feat

#109 🔗 :: (#108) 마이페이지 Section 리팩토링
  Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/BugSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/SectionView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
Labels: ✨feat, ♻️refactor

#113 🔗 :: (#111) Presentation/Base 수정
  Projects/Modules/DesignSystem/Sources/Label/JobisMenuLabel.swift
  Projects/Modules/DesignSystem/Sources/Lottie/JobisLottieView.swift
  Projects/Modules/DesignSystem/Sources/Toast/JobisToast.swift
  Projects/Modules/DesignSystem/Sources/View/StudentInfoView.swift
  Projects/Presentation/Sources/Base/BaseTabBarController.swift
  Projects/Presentation/Sources/Base/BaseTableViewCell.swift
  Projects/Presentation/Sources/Base/BaseView.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Base/Protocol/AddViewable.swift
  Projects/Presentation/Sources/Base/Protocol/Bindable.swift
  Projects/Presentation/Sources/Base/Protocol/HasBounds.swift
  Projects/Presentation/Sources/Base/Protocol/HasDisposeBag.swift
  Projects/Presentation/Sources/Base/Protocol/LifeCyclePublishable.swift
  Projects/Presentation/Sources/Base/Protocol/NavigationConfigurable.swift
  Projects/Presentation/Sources/Base/Protocol/SetLayoutable.swift
  Projects/Presentation/Sources/Base/Protocol/ViewConfigurable.swift
  Projects/Presentation/Sources/Base/Protocol/ViewControllable.swift
  Projects/Presentation/Sources/Base/Protocol/ViewControllerConfigurable.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
  Projects/Presentation/Sources/Home/Components/Cell/EmptyApplicationView.swift
  Projects/Presentation/Sources/Home/Components/EmploymentView.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/BugSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/ReviewNavigateView.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/SectionTableViewCell.swift
  Projects/Presentation/Sources/MyPage/Components/SectionView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewController.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
  Projects/Presentation/Sources/Signup/InfoSetting/InfoSettingViewController.swift
  Projects/Presentation/Sources/Signup/PasswordSetting/PasswordSettingViewController.swift
  Projects/Presentation/Sources/Signup/Privacy/PrivacyViewController.swift
  Projects/Presentation/Sources/Signup/VerifyEmail/VerifyEmailViewController.swift
Labels: ♻️refactor

#116 🔗 :: (#115) SectionView 리팩토링
  Projects/Modules/DesignSystem/Sources/Label/JobisMenuLabel.swift
  Projects/Presentation/Sources/MyPage/Components/AccountSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/BugSectionView.swift
  Projects/Presentation/Sources/MyPage/Components/SectionView.swift
Labels: ♻️refactor

#119 🔗 :: (#117) 함수 호출 위치 변경
  Projects/Presentation/Sources/Base/BaseView.swift
Labels: ♻️refactor

#120 🔗 :: (#118) JOBIS Swift Style Guide에 맞게 리펙토링
  Projects/Flow/Sources/AppFlow.swift
  Projects/Flow/Sources/AppStepper.swift
  Projects/Flow/Sources/Onboarding/OnboardingFlow.swift
  Projects/Flow/Sources/Signin/SigninFlow.swift
  Projects/Flow/Sources/Signup/InfoSettingFlow.swift
  Projects/Flow/Sources/Signup/PasswordSettingFlow.swift
  Projects/Flow/Sources/Signup/PrivacyFlow.swift
  Projects/Flow/Sources/Signup/VerifyEmailFlow.swift
  Projects/Flow/Sources/Tabs/BookmarkFlow.swift
  Projects/Flow/Sources/Tabs/Home/AlarmFlow.swift
  Projects/Flow/Sources/Tabs/Home/HomeFlow.swift
  Projects/Flow/Sources/Tabs/MyPageFlow.swift
  Projects/Flow/Sources/Tabs/RecruitmentFlow.swift
  Projects/Flow/Sources/Tabs/TabsFlow.swift
  Projects/Modules/DesignSystem/Sources/Button/JobisButton.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UIViewController/UIViewController+showJobisToast.swift
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Modules/DesignSystem/Sources/Image/TextFieldIcon.swift
  Projects/Modules/DesignSystem/Sources/TextField/Component/DescriptionView.swift
  Projects/Modules/DesignSystem/Sources/TextField/Component/TextFieldRightStackView.swift
  Projects/Modules/DesignSystem/Sources/TextField/JobisTextField.swift
  Projects/Modules/DesignSystem/Sources/TextField/Type/DescriptionType.swift
  Projects/Modules/DesignSystem/Sources/UITabBarItem/JobisTabBarItem.swift
  Projects/Presentation/Sources/Base/BaseNavigationController.swift
  Projects/Presentation/Sources/Base/BaseReactorViewController.swift
  Projects/Presentation/Sources/Base/BaseViewController.swift
  Projects/Presentation/Sources/Bookmark/BookmarkViewModel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
  Projects/Presentation/Sources/Home/Alarm/AlarmViewModel.swift
  Projects/Presentation/Sources/Home/Alarm/Cell/AlarmTableViewCell.swift
  Projects/Presentation/Sources/Home/Components/CareerNavigationCard.swift
  Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusTableViewCell.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/ReviewNavigateView.swift
  Projects/Presentation/Sources/MyPage/Components/Cell/SectionTableViewCell.swift
  Projects/Presentation/Sources/MyPage/Components/SectionView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewController.swift
  Projects/Presentation/Sources/Onboarding/OnboardingViewModel.swift
  Projects/Presentation/Sources/Signin/SigninReactor.swift
  Projects/Presentation/Sources/Signup/InfoSetting/InfoSettingViewController.swift
  Projects/Presentation/Sources/Signup/InfoSetting/InfoSettingViewModel.swift
  Projects/Presentation/Sources/Signup/PasswordSetting/PasswordSettingViewController.swift
  Projects/Presentation/Sources/Signup/PasswordSetting/PasswordSettingViewModel.swift
  Projects/Presentation/Sources/Signup/Privacy/PrivacyViewController.swift
  Projects/Presentation/Sources/Signup/Privacy/PrivacyViewModel.swift
  Projects/Presentation/Sources/Signup/VerifyEmail/VerifyEmailViewController.swift
  Projects/Presentation/Sources/Signup/VerifyEmail/VerifyEmailViewModel.swift
Labels: ♻️refactor

#123 🔗 :: (#122) 디자인 변경에 따라 home뷰 수정
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/CurrentPageControl.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/CurrentPageControl.imageset/Rectangle 371.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/DefaultPageControl.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/DefaultPageControl.imageset/Rectangle 369.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Jobis Logo.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Jobis Logo.imageset/Frame 2080012444.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Pie Chart.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Pie Chart.imageset/Pie Chart.svg
  Projects/Modules/DesignSystem/Sources/Extensions/UILabel/UILabe+setColorRange.swift
  Projects/Modules/DesignSystem/Sources/Extensions/UILabel/UILabe+setRangeOfText.swift
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Modules/DesignSystem/Sources/Label/JobisMenuLabel.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Sources/Base/BaseTableViewCell.swift
  Projects/Presentation/Sources/Home/Components/BannerView.swift
  Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusTableViewCell.swift
  Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift
  Projects/Presentation/Sources/Home/Components/Cell/EmploymentCollectionViewCell.swift
  Projects/Presentation/Sources/Home/Components/EmploymentView.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
  Projects/Presentation/Sources/MyPage/Components/SectionView.swift
  Projects/Presentation/Sources/Signin/SigninViewController.swift
  Tuist/Dependencies.swift
Labels: ✨feat

#127 🔗 :: (#126) Haptic 추가
  Projects/Presentation/Sources/Base/BaseTabBarController.swift
Labels: ✨feat

#129 🔗 :: (#128) 북마크 퍼블리싱
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Empty Bookmark.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Empty Bookmark.imageset/Expressionless face.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Current Page Control.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Current Page Control.imageset/Rectangle 371.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Default Page Control.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Home/Default Page Control.imageset/Rectangle 369.svg
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Trash.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images/Icons.xcassets/Trash.imageset/delete.svg
  Projects/Modules/DesignSystem/Sources/Button/JobisButton.swift
  Projects/Modules/DesignSystem/Sources/Image/JobisIcon.swift
  Projects/Presentation/Sources/Bookmark/BookmarkViewController.swift
  Projects/Presentation/Sources/Bookmark/BookmarkViewModel.swift
  Projects/Presentation/Sources/Bookmark/Cell/BookmarkTableViewCell.swift
  Projects/Presentation/Sources/Bookmark/Component/EmptyBookmarkView.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
Labels: ✨feat

#125 🔗 :: (#124) BaseCollectionViewCell
  Projects/Presentation/Sources/Base/BaseCollectionViewCell.swift
  Projects/Presentation/Sources/Home/Components/BannerView.swift
  Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift
  Projects/Presentation/Sources/Home/Components/Cell/EmploymentCollectionViewCell.swift
Labels: ✨feat
