Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2024-04, with the labels that each got.

#219 🔗 :: (#214) 가로 회전 막기
  Projects/App/Support/Info.plist
Labels: ✨feat

#221 🔗 :: (#216) 모집의뢰서 상세 모집 분야 버그 수정
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewController.swift
  Projects/Presentation/Sources/RecruitmentDetail/RecruitmentDetailViewModel.swift
Labels: 👾bug

#222 🔗 :: (#215) 기업 탐색 클래스 명 수정 및 버그 개선
  Projects/Core/Sources/Steps/CompanySearchStep.swift
  Projects/Core/Sources/Steps/CompanyStep.swift
  Projects/Core/Sources/Steps/HomeStep.swift
  Projects/Flow/Sources/Company/CompanyFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Presentation/Sources/CompanySearch/Cell/CompanyTableViewCell.swift
  Projects/Presentation/Sources/CompanySearch/CompanyViewController.swift
  Projects/Presentation/Sources/CompanySearch/CompanyViewModel.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
Labels: 👾bug, ♻️refactor

#224 🔗 :: (#217) 커스텀 Alert
  Projects/Modules/DesignSystem/Sources/Alert/AlertBuilder.swift
  Projects/Modules/DesignSystem/Sources/Alert/AlertButton.swift
  Projects/Modules/DesignSystem/Sources/Alert/AlertButtonStyle.swift
  Projects/Modules/DesignSystem/Sources/Alert/JobisAlertViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
Labels: ✨feat

#244 🔗 :: (#220) 기업 상세 리펙토링
  Projects/Presentation/Sources/CompanyDetail/CompanyDetailViewController.swift
  Projects/Presentation/Sources/CompanyDetail/Components/CompanyDetailLabel.swift
  Projects/Presentation/Sources/CompanyDetail/Components/CompanyDetailProfileView.swift
Labels: ♻️refactor

#248 🔗 :: (#227) recruitmentsearch -> searchrecruitment
  Projects/Core/Sources/Steps/RecruitmentSearchStep.swift
  Projects/Core/Sources/Steps/RecruitmentStep.swift
  Projects/Core/Sources/Steps/SearchRecruitmentStep.swift
  Projects/Flow/Sources/Recruitment/RecruitmentFlow.swift
  Projects/Flow/Sources/Recruitment/RecruitmentSearchFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Recruitment/RecruitmentViewModel.swift
  Projects/Presentation/Sources/SearchRecruitment/SearchRecruitmentViewController.swift
  Projects/Presentation/Sources/SearchRecruitment/SearchRecruitmentViewModel.swift
Labels: ♻️refactor
