Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2025-03, with the labels that each got.

#279 개발자 소개 수정
  README.md
Labels: 📝docs

#276 🔗 :: (#275) 반 별 취업 현황 API 연동
  Projects/Core/Sources/Steps/EmployStatusStep.swift
  Projects/Data/Sources/DI/UseCaseAssembly.swift
  Projects/Data/Sources/DTO/Applications/ClassEmploymentListResponseDTO.swift
  Projects/Data/Sources/DataSource/API/ApplicationsAPI.swift
  Projects/Data/Sources/DataSource/Remote/RemoteApplicationsDataSource.swift
  Projects/Data/Sources/Repositories/ApplicationsRepositoryImpl.swift
  Projects/Domain/Sources/Entities/Applications/EmploymentEntity.swift
  Projects/Domain/Sources/Repositories/ApplicationsRepository.swift
  Projects/Domain/Sources/UseCases/Applications/FetchEmploymentStatusUseCase.swift
  Projects/Flow/Sources/Home/EmployStatusFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/EmployStatus/ClassEmploymentViewController.swift
  Projects/Presentation/Sources/Home/EmployStatus/ClassEmploymentViewModel.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ClassButton.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ClassCategory.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ClassCollectionViewCell.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ClassEmploymentCollectionViewLayout.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewModel.swift
Labels: ✨feat

#281 🔗 :: (#280) 지원하기 버튼 활성화 오류 해결
  Projects/Presentation/Sources/Apply/ApplyViewModel.swift
Labels: 👾bug

#284 🔗 :: (#283) 공지사항 오류 수정
  Projects/Data/Sources/DTO/Notice/NoticeDetailResponseDTO.swift
  Projects/Domain/Sources/Enums/AttachmentType.swift
  Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift
Labels: 👾bug

#285 🔗 :: (#282) 프로필 수정 기능 추가
  Projects/Modules/DesignSystem/Sources/View/StudentInfoView.swift
  Projects/Presentation/Sources/MyPage/MyPageViewController.swift
  Projects/Presentation/Sources/MyPage/MyPageViewModel.swift
Labels: ✨feat
