Repository Team-return/JOBIS-DSM-iOS-v2, pull requests merged in 2025-02, with the labels that each got.

#267 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ⚙️setting

#268 🔗 :: (#266) 취업률 배너 수정
  Projects/Core/Sources/Steps/EmployStatusStep.swift
  Projects/Core/Sources/Steps/HomeStep.swift
  Projects/Flow/Sources/Home/EmployStatusFlow.swift
  Projects/Flow/Sources/Home/HomeFlow.swift
  Projects/Presentation/Sources/DI/PresentationAssembly.swift
  Projects/Presentation/Sources/Home/Components/Cell/BannerCollectionViewCell.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewModel.swift
  Projects/Presentation/Sources/Home/HomeViewController.swift
  Projects/Presentation/Sources/Home/HomeViewModel.swift
Labels: ♻️refactor

#270 🔗 :: (#269) ChartView 구현
  .package.resolved
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/DesignSystem/Resources/Colors/Sub.xcassets/SkyBlue 30.colorset/Contents.json
  Projects/Modules/DesignSystem/Sources/Color/UIColor+Sub.swift
  Projects/Modules/DesignSystem/Sources/Typography/JobisFont.swift
  Projects/Modules/DesignSystem/Sources/Typography/JobisFontStyle.swift
  Projects/Modules/DesignSystem/Sources/UITabBarItem/JobisTabBarItem.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/LegendView.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift
  Tuist/Dependencies.swift
Labels: ✨feat

#274 🔗 :: (#273) 반 별 취업 현황 보기 버튼
  Projects/Modules/DesignSystem/Sources/Typography/JobisFont.swift
  Projects/Modules/DesignSystem/Sources/Typography/JobisFontStyle.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ChartView.swift
  Projects/Presentation/Sources/Home/EmployStatus/Components/ClassButton.swift
  Projects/Presentation/Sources/Home/EmployStatus/EmployStatusViewController.swift
Labels: ✨feat
